version: "3.7"

x-service-base: &service-base
  restart: unless-stopped
  env_file: .env
  logging:
    driver: "json-file"
    options:
      max-size: "1m"
      max-file: "10"
  networks:
    - db-net

services:
  sagira:
    <<: *service-base
    image: "ghostofgoes/sagira-bot:latest"
    build:
      context: .
      dockerfile: Dockerfile
      cache_from: ["ghostofgoes/sagira-bot:latest"]
    container_name: sagira
    init: true
    volumes:
      - bot_log:/sagira/log
      - bot_data:/sagira/data
  # db:
  #   <<: *service-base
  #   image: "mongo:4.4-bionic"
  #   container_name: db
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
  #     - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
  #     - MONGO_HOSTNAME=db
  #   volumes:
  #     - dbdata:/data/db

networks:
  db-net:
    driver: bridge

volumes:
  dbdata:
  bot_log:
  bot_data:
