version: "3.7"

x-service-base: &service-base
  restart: unless-stopped
  env_file: .env
  logging:
    driver: "json-file"
    options:
      max-size: "1m"
      max-file: "10"
  networks:
    - es-net

services:
  bot:
    <<: *service-base
    image: "ghostofgoes/sagira-bot:latest"
    build:
      context: .
      dockerfile: Dockerfile
      cache_from: ["ghostofgoes/sagira-bot:latest"]
    container_name: bot
    init: true
    volumes:
      - bot_logs:/sagira/logs
      - bot_data:/sagira/data
  # TODO: add elastic

networks:
  es-net:
    driver: bridge

volumes:
  bot_logs:
  bot_data:
