version: "3.7"

x-service-base: &service-base
  restart: unless-stopped
  env_file: .env
  logging:
    driver: "json-file"
    options:
      max-size: "1m"
      max-file: "10"
  networks:
    - es-net

# TODO: Add TLS certificates (and add steps to README on how to generate certs)
# https://www.elastic.co/guide/en/elasticsearch/reference/current/security-basic-setup.html
# https://www.elastic.co/guide/en/elasticsearch/reference/current/certutil.html
# https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html


services:
  bot:
    <<: *service-base
    image: "ghostofgoes/sagira-bot:latest"
    build:
      context: .
      dockerfile: Dockerfile
      cache_from: ["ghostofgoes/sagira-bot:latest"]
    container_name: bot
    init: true
    volumes:
      - bot-logs:/sagira/logs
      - bot-data:/sagira/data
  elasticsearch:
    <<: *service-base
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    container_name: elasticsearch
    environment:
      - cluster.name=sagira-cluster
      - node.name=sagira-elastic
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.monitoring.collection.enabled=true
      - xpack.license.self_generated.type=basic
      # TODO: enable security once we have certificates setup
      # - xpack.security.transport.ssl.enabled=true
      # - xpack.security.enabled=true
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      # TODO: increase memory limits in production
      - ES_JAVA_OPTS=-Xms2g -Xmx2g -Des.enforce.bootstrap.checks=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
  kibana:
    <<: *service-base
    image: docker.elastic.co/kibana/kibana:8.1.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
    # TODO: configure kibana security, including a username/password\
    # https://www.elastic.co/guide/en/kibana/current/using-kibana-with-security.html
      - elasticsearch.hosts=https://elasticsearch:9200
      - elasticsearch.username=kibana_system
      - elasticsearch.password=${KIBANA_PASSWORD}
      - telemetry.optIn=false
      - telemetry.enabled=false
      - xpack.apm.ui.enabled=false
      - xpack.monitoring.collection.enabled=true
      - monitoring.ui.enabled=true
      - monitoring.ui.container.elasticsearch.enabled=true
    volumes:
      - kibana-data:/usr/share/kibana/data

networks:
  es-net:
    driver: bridge

volumes:
  bot-logs:
  bot-data:
  es-data:
  kibana-data:
